### PR TITLE
Added consumption artifact action to blood

### PR DESCRIPTION
**Pull request by cmmoran**
Single-target, cleave, and aoe profiles for blood. Priority taken from icy-veins.

### CODE REVIEW

**Comment by tzarc** [comment]
Thanks for that - unfortunately this'll get overwritten next time I get around to updating the APLs from other classes... if you can make the same changes to _Support/CustomProfiles/deathknight_blood.simc_, I'll merge it straight up.

**Comment by cmmoran** [comment]
Sorry about that. I honestly didn't know your process for building a release. I suppose I should have done a bit more research into your codebase before making a change to it :).

Either way, I'm actually currently using the profile changes live and they work perfectly. I have not tested the simc profile change but I'm almost positive it will work just fine. (Famous last words I know)

**Comment by tzarc** [comment]
No problem! Just figured I should at least give you the proper credit for it, is all :)
Thanks again!

**Comment by tzarc** [comment]
Tagged under **70100.058-alpha.002** - need to run through other classes to test the precombat change, so it'll tagged in a proper release soonish. Cheers!

**Pull request merged**
